---

- name: Delete OpenShift 4 Environment
  hosts: localhost
  gather_facts: no
  vars:
    master_ips: []
    worker_ips: []
  vars_files:
    - ocp4_vars.yml
    - passwd.yml

  tasks:
    - name: Collect master ips
      set_fact:
        master_ips: "{{ master_ips + [hostvars[item]['ansible_host']] }}"
      loop: "{{ groups['masters'] }}"

    - name: Collect worker ips
      set_fact:
        worker_ips: "{{ worker_ips + [hostvars[item]['ansible_host']] }}"
      loop: "{{ groups['workers'] }}"

    - name: Install terraform
      include_tasks: terraform_install.yml

    - name: Destroy VMs 
      terraform:
        binary_path: "{{ terraform['binary_path'] }}/terraform"
        project_path: "{{ terraform['project_path'] }}"
        state: absent
        variables:
          ocp_version: "4"
          image_path: "{{ terraform['image_path'] }}"
          memory: "{{ terraform['memory'] }}"
          vcpu: "{{ terraform['vcpu'] }}"
          domain: "{{ network['domain'] }}"
          dns:  "{{ network['dns'] }}"
          interface: "{{ network['interface'] }}"
          bootstrap_ip: "{{ hostvars[ (groups['bootstrap'][0]) ]['ansible_host']}}"
          master_ips: "{{ master_ips | join(',') }}"
          worker_ips: "{{ worker_ips | join(',') }}"
          cidr:  "{{ network['cidr'] }}"
          gateway:  "{{ network['gateway'] }}"
          dns:  "{{ network['dns'] }}"
      run_once: true

    - name: Remove public keys from known_hosts (ips)
      known_hosts:
        name: "{{ ansible_host }}"
        path: "{{ lookup('env','HOME') }}/.ssh/known_hosts"
        state: absent
      throttle: 1

    - name: Remove public keys from known_hosts (hostnames)
      known_hosts:
        name: "{{ item }}"
        path: "{{ lookup('env','HOME') }}/.ssh/known_hosts"
        state: absent
      throttle: 1
      loop: "{{ query('inventory_hostnames', 'all') }}"
